common = [ # LVL 1
"Potion of Climbing",
"Common Potion of Healing",
"Spell Scroll"
]

uncommon = [ # LVL 1
"Adamantine Armor",
"Ammunition, +1",
"Amulet of Proof against Detection and Location",
"Bag of Holding",
"Bag of Tricks",
"Boomerang, +1",
"Boots of Elvenkind",
"Boots of Striding and Springing",
"Boots of the Winterlands",
"Bracers of Archery",
"Brooch of Shielding",
"Broom of Flying",
"Circlet of Blasting",
"Cloack of Elvenkind",
"Cloak of Protection",
"Cloak of the Manta Ray",
"Decanter of Endless Water",
"Deck of Illusions",
"Dust of Disappearance",
"Dust of Dryness",
"Dust of Sneezing and Choking",
"Efficient Quiver",
"Elemental Gem",
"Eversmoking Bottle",
"Eyes of Charming",
"Eyes of Minute Seeing",
"Eyes of the Eagle",
"Figuring of Wondrous Power",
"Gauntlets of Ogre Power",
"Gem of Brightness",
"Gloves of Missile Snaring",
"Gloves of Swimming and Climbing",
"Goggles of Night",
"Hat of Disguise",
"Headband of Intellect",
"Helm of Comprehending Languages",
"Helm of Telepathy",
"Immovable Rod",
"Javelin of Lightning",
"Lantern of Revealing",
"Medallion of Thoughts",
"Mithril Armor",
"Necklace of Adaptation",
"Oil of Slipperiness",
"Pearl of Power",
"Periapt of Health",
"Periapt of Wound Closure",
"Philter of Love",
"Pipes of Haunting",
"Pipes of the Sewers",
"Potion of Animal Friendship",
"Potion of Giant Strength",
"Potion of Growth",
"Uncommon Potion of Healing",
"Potion of Poison",
"Potion of Resistance",
"Potion of Water Breathing",
"Restorative Ointment",
"Ring of Jumping",
"Ring of Mind Shielding",
"Ring of Swimming",
"Ring of Warmth",
"Ring of Water Walking",
"Robe of Useful Items",
"Rope of Climbing",
"Shield, +1",
"Slippers of Spider Climbing",
"Spell Scroll +1",
"Staff of the Python",
"Stone of Good Luck (Luckstone)",
"Trident of Fish Command",
"Wand of Magic Detection",
"Wand of Magic Missiles",
"Wand of Secrets",
"Wand of the War Mage",
"Wand of Web",
"Weapon, +1",
"Wind Fan",
"Winged Boots"
]

rare = [ # LVL 5
"TO BE ADDED"
]

veryRare = [ # LVL 11
"TO BE ADDED"
]

legendary = [ # LVL 17
"Apparatus of the Crab",
"Armor of Invulnerability",
"Armor, +3",
"Belt of Giant Strength",
"Crystal Ball of Mind Reading",
"Crystal Ball of Telepathy",
"Crystal Ball of True Seeing",
"Cubic Gate",
"Deck of Many Things",
"Defender",
"Hammer of Thunderbolts"
"Holy Avenger",
"Ioun Stone",
"Iron Flask",
"Luck Blade",
"Plate Armor of Etherealness",
"Potion of Giant Strength",
"Ring of Air Elemental Command",
"Ring of Djinni Summoning",
"Ring of Earth Elemental Command",
"Ring of Elemental Command",
"Ring the Fire Elemental Command",
"Ring of Invisibility",
"Ring of Spell Turning",
"Ring of Three Wishes",
"Ring of Water Elemental Command",
"Robe of the Archmagi",
"Rod of Lordly Might",
"Scarab of Protection",
"Sovereign Glue",
"Spell Scroll +3",
"Sphere of Annihilation",
"Staff of the Magi",
"Talisman of Pure Good",
"Talisman of the Sphere",
"Talisman of Ultimate Evil",
"Universal Solvent",
"Vorpal Sword",
"Well of Many Worlds"
]

artifact = [ # SPECIAL :)
"Adze of Annam",
"Akmon, Hammer of Purphoros",
"Axe of the Dwarvish Lords",
"Baba Yaga's Mortar and Pestle",
"Bigby's Beneficent Bracelet",
"Blade of Avernus",
"Book of Exhalted Deeds",
"Book of Vile Darkness",
"Crook of Rao",
"Dekella, Bident of Thassa",
"Demonomicon of Iggwilv",
"Draakhorn",
"Ephixis, Bow of Nylea",
"Eye and Hand of Vecna",
"Helm of Perfect Potential",
"Iggwilv's Cauldron",
"Khrusor, Spear of Heliod",
"Luba's Tarokka of Souls",
"Mask of the Dragon Queen",
"Mastix, Whip of Erebos",
"Mighty Servant of Leuk-o",
"Orb of Dragonkind",
"Orrery of the Wanderer",
"Ring of Winter",
"Ruinstone",
"Staff of the Forgotten One",
"Stone of Golorr",
"Sword of Kas",
"Sword of Zariel",
"Teeth of Dahlver-Nar",
"The Infernal Machine of Lum the Mad",
"Wand of Orcus",
"Wyrmskull Throne"
]