common = [ # LVL 1
"Potion of Climbing",
"Common Potion of Healing",
"Spell Scroll"
]

uncommon = [ # LVL 1
"Adamantine Armor",
"Ammunition, +1",
"Amulet of Proof against Detection and Location",
"Bag of Holding",
"Bag of Tricks",
"Boomerang, +1",
"Boots of Elvenkind",
"Boots of Striding and Springing",
"Boots of the Winterlands",
"Bracers of Archery",
"Brooch of Shielding",
"Broom of Flying",
"Circlet of Blasting",
"Cloack of Elvenkind",
"Cloak of Protection",
"Cloak of the Manta Ray",
"Decanter of Endless Water",
"Deck of Illusions",
"Dust of Disappearance",
"Dust of Dryness",
"Dust of Sneezing and Choking",
"Efficient Quiver",
"Elemental Gem",
"Eversmoking Bottle",
"Eyes of Charming",
"Eyes of Minute Seeing",
"Eyes of the Eagle",
"Figuring of Wondrous Power",
"Gauntlets of Ogre Power",
"Gem of Brightness",
"Gloves of Missile Snaring",
"Gloves of Swimming and Climbing",
"Goggles of Night",
"Hat of Disguise",
"Headband of Intellect",
"Helm of Comprehending Languages",
"Helm of Telepathy",
"Immovable Rod",
"Javelin of Lightning",
"Lantern of Revealing",
"Medallion of Thoughts",
"Mithril Armor",
"Necklace of Adaptation",
"Oil of Slipperiness",
"Pearl of Power",
"Periapt of Health",
"Periapt of Wound Closure",
"Philter of Love",
"Pipes of Haunting",
"Pipes of the Sewers",
"Potion of Animal Friendship",
"Potion of Giant Strength",
"Potion of Growth",
"Uncommon Potion of Healing",
"Potion of Poison",
"Potion of Resistance",
"Potion of Water Breathing",
"Restorative Ointment",
"Ring of Jumping",
"Ring of Mind Shielding",
"Ring of Swimming",
"Ring of Warmth",
"Ring of Water Walking",
"Robe of Useful Items",
"Rope of Climbing",
"Shield, +1",
"Slippers of Spider Climbing",
"Spell Scroll +1",
"Staff of the Python",
"Stone of Good Luck (Luckstone)",
"Trident of Fish Command",
"Wand of Magic Detection",
"Wand of Magic Missiles",
"Wand of Secrets",
"Wand of the War Mage",
"Wand of Web",
"Weapon, +1",
"Wind Fan",
"Winged Boots"
]

rare = [ # LVL 5
"Ammunition, +2",
"Amulet of Health",
"Armor of Resistance",
"Armor of Vulnerability",
"Armor, +1",
"Arrow-Catching Shield",
"Bag of Beans",
"Bead of Force",
"Belt of Dwarvenkind",
"Belt of Giant Strength",
"Beserker Axe",
"Boomerang, +2",
"Boots of Levitation",
"Boots of Speed",
"Bowl of Commanding Water Elementals",
"Bracers of Defense",
"Brazier of Commanding Fire Elementals",
"Cape of the Mountebank",
"Censer of Controlling Air Elemental",
"Chime of Opening",
"Cloak of Displacement",
"Cloak of the Bat",
"Cube of Force",
"Dagger of Venom",
"Dimensional Shackles",
"Dragon Slayer",
"Elven Chain",
"Feather Token",
"Figurine of Wondrous Power",
"Flame Tongue",
"Folding Boat",
"Gem of Seeing",
"Giant Slayer",
"Glamoured Studded Leather",
"Handy Haversack",
"Helm of Teleportation",
"Horn of Blasting",
"Horn of Valhalla",
"Horseshoes of Speed",
"Instant Fortress",
"Ioun Stone",
"Iron Bands of Binding",
"Mace of Disruption",
"Mace of Smiting",
"Mace of Terror",
"Mantle of Spell Resistance",
"Master's Amulet",
"Necklace of Fireballs",
"Necklace of Prayer Beads",
"Oil of Etherealness",
"Periapt of Proof against Poison",
"Portable Hole",
"Potion of Clairvoyance",
"Potion of Diminution",
"Potion of Gaseous Form",
"Potion of Giant Strength",
"Rare Potion of Healing",
"Potion of Heroism",
"Potion of Mind Reading",
"Ring of Animal Influence",
"Ring of Evasion",
"Ring of Feather Falling",
"Ring of Free Action",
"Ring of Protection",
"Ring of Resistance",
"Ring of Spell Storing",
"Ring of the Ram",
"Ring of X-ray Vision",
"Robe of Eyes",
"Rod of Rulership",
"Rope of Entaglement",
"Shield of Missile Attraction",
"Shield, +2",
"Spell Scroll +2",
"Staff of Charming",
"Staff of Healing",
"Staff of Swarming Insects",
"Staff of the Woodlands",
"Staff of Withering",
"Stone of Controlling Eath Elementals",
"Sun Blade",
"Sword of Life Stealing",
"Sword of Wounding",
"Vicious Weapon",
"wand of Binding",
"Wand of Enemy Detection",
"Wand of Fear",
"Wand of Fireballs",
"Wand of Lightning Bolts",
"Wand of Paralysis",
"Wand of the War Mage",
"Wand of Wonder",
"Weapon, +2",
"Wings of Flying"
]

veryRare = [ # LVL 11
"Ammunition, +3",
"Amulet of the Planes",
"Animated Shield",
"Armor, +2",
"Arrow of Slaying",
"Bag of Devouring",
"Belt of Giant Strenght",
"Boomerang, +3",
"Candle of Invocation",
"Carpet of Flying",
"Cloak of Arachnida",
"Crystal Ball",
"Dancing Sword",
"Demon Armor",
"Dragon Scale Mail",
"Dwarven Plate",
"Dwarven Thrower",
"Efreeti Bottle",
"Figurine of Wondrous Power",
"Frost Brand",
"Helm of Brilliance",
"Horn of Valhalla",
"Horseshoes of a Zephyr",
"Ioun Stone",
"Manual of Bodily Health",
"Manual of Gainful Exercise",
"Manual of Golems",
"Manual of Quickness of Action",
"Marvelous Pigments",
"Mirror of Life Trapping",
"Nine Lives Stealer",
"Oathbow",
"Oil of Sharpness",
"Potion of Flying",
"Potion of Giant Strength",
"Very Rare Potion of Healing",
"Potion of Invisibility",
"Potion of Speed",
"Potion of Vitality",
"Ring of Regeneration",
"Ring of Shooting Stars",
"Ring of Telekinesis",
"Robe of Scintillating Colors",
"Robe of Stars",
"Rod of Absorption",
"Rod of Alertness",
"Rod of Security",
"Scimitar of Speed",
"Shield, +3",
"Spell Scroll",
"Spellguard Shield",
"Staff of Fire",
"Staff of Frost",
"Staff of Power",
"Staff of Striking",
"Staff of Thunder and Lightning",
"Sword of Sharpness",
"Tome of Clear Thought",
"Tome of Leadership and Influence",
"Tome of Understanding",
"Wand of Polymorph",
"Wand of the War Mage",
"Weapon, +3"
]

legendary = [ # LVL 17
"Apparatus of the Crab",
"Armor of Invulnerability",
"Armor, +3",
"Belt of Giant Strength",
"Crystal Ball of Mind Reading",
"Crystal Ball of Telepathy",
"Crystal Ball of True Seeing",
"Cubic Gate",
"Deck of Many Things",
"Defender",
"Hammer of Thunderbolts",
"Holy Avenger",
"Ioun Stone",
"Iron Flask",
"Luck Blade",
"Plate Armor of Etherealness",
"Potion of Giant Strength",
"Ring of Air Elemental Command",
"Ring of Djinni Summoning",
"Ring of Earth Elemental Command",
"Ring of Elemental Command",
"Ring the Fire Elemental Command",
"Ring of Invisibility",
"Ring of Spell Turning",
"Ring of Three Wishes",
"Ring of Water Elemental Command",
"Robe of the Archmagi",
"Rod of Lordly Might",
"Scarab of Protection",
"Sovereign Glue",
"Spell Scroll +3",
"Sphere of Annihilation",
"Staff of the Magi",
"Talisman of Pure Good",
"Talisman of the Sphere",
"Talisman of Ultimate Evil",
"Universal Solvent",
"Vorpal Sword",
"Well of Many Worlds"
]

artifact = [ # SPECIAL :)
"Adze of Annam",
"Akmon, Hammer of Purphoros",
"Axe of the Dwarvish Lords",
"Baba Yaga's Mortar and Pestle",
"Bigby's Beneficent Bracelet",
"Blade of Avernus",
"Book of Exhalted Deeds",
"Book of Vile Darkness",
"Crook of Rao",
"Dekella, Bident of Thassa",
"Demonomicon of Iggwilv",
"Draakhorn",
"Ephixis, Bow of Nylea",
"Eye and Hand of Vecna",
"Helm of Perfect Potential",
"Iggwilv's Cauldron",
"Khrusor, Spear of Heliod",
"Luba's Tarokka of Souls",
"Mask of the Dragon Queen",
"Mastix, Whip of Erebos",
"Mighty Servant of Leuk-o",
"Orb of Dragonkind",
"Orrery of the Wanderer",
"Ring of Winter",
"Ruinstone",
"Staff of the Forgotten One",
"Stone of Golorr",
"Sword of Kas",
"Sword of Zariel",
"Teeth of Dahlver-Nar",
"The Infernal Machine of Lum the Mad",
"Wand of Orcus",
"Wyrmskull Throne"
]